// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetItems() {
  return window['go']['xiaohongshu']['Xiaohongshu']['GetItems']();
}

export function NextPage() {
  return window['go']['xiaohongshu']['Xiaohongshu']['NextPage']();
}

export function OnDomReady(arg1) {
  return window['go']['xiaohongshu']['Xiaohongshu']['OnDomReady'](arg1);
}

export function OnItemClick(arg1) {
  return window['go']['xiaohongshu']['Xiaohongshu']['OnItemClick'](arg1);
}

export function Refresh() {
  return window['go']['xiaohongshu']['Xiaohongshu']['Refresh']();
}

export function Startup(arg1) {
  return window['go']['xiaohongshu']['Xiaohongshu']['Startup'](arg1);
}
