// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetItems():Promise<Array<Record<string, any>>>;

export function NextPage():Promise<void>;

export function OnDomReady(arg1:context.Context):Promise<void>;

export function OnItemClick(arg1:number):Promise<void>;

export function Refresh():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
